### ISSUE TITLE
Doesn't compile with Xcode 8 beta 2

### ISSUE THREAD

**Issue by danil-z** [aciidb0mb3r/Spawn#1]
Spawn.swift:88:35: Cannot convert value of type '(x: UnsafeMutablePointer<Void>?) -> UnsafeMutablePointer<Void>?' to expected argument type '@convention(c) (UnsafeMutablePointer<Void>) -> UnsafeMutablePointer<Void>!'

**Comment by aciidgh** [comment]
Should be fixed now, thanks for reporting
